export { default as Recommend } from './Recommend'
export { default as Community } from './Community'
export { default as Tutorial } from './Tutorial'
export { default as Mypage } from './Mypage'
export { default as Pattern } from './Pattern'
