* [32mdev[m
  docs/BE/update-erd[m
  feat/BE/com-list[m
  feat/BE/comm-likes[m
  feat/BE/community[m
  feat/BE/data-refine[m
  feat/BE/dataImg-refine[m
  feat/BE/db-dev[m
  feat/BE/db-import[m
  feat/BE/db-model[m
  feat/BE/dev-db[m
  feat/BE/jarang-board[m
  feat/BE/jarangImg[m
  feat/BE/likes[m
  feat/BE/recommend-memberBased[m
  feat/BE/user-recommend[m
  feat/FE/recommend_molecule[m
  main[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/dev[m
  [31mremotes/origin/feat/BE/community[m
  [31mremotes/origin/feat/BE/crawling[m
  [31mremotes/origin/feat/BE/entity[m
  [31mremotes/origin/feat/BE/likes[m
  [31mremotes/origin/feat/BE/recommand-contents[m
  [31mremotes/origin/feat/BE/search-BoardAndPattern[m
  [31mremotes/origin/feat/FE/communitygroup[m
  [31mremotes/origin/feat/FE/imageHandler[m
  [31mremotes/origin/feat/FE/mainpage[m
  [31mremotes/origin/feat/FE/mypageAll[m
  [31mremotes/origin/feat/FE/recommend-pattern[m
  [31mremotes/origin/feat/FE/selectyarn[m
  [31mremotes/origin/feat/FE/tutorialAssets[m
  [31mremotes/origin/feat/release[m
  [31mremotes/origin/main[m
  [31mremotes/origin/release[m
  [31mremotes/origin/rename/BE/change-folder[m
  [31mremotes/origin/test/BE/develop[m
