/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 purl_2_complete-transformed.glb -t
*/

import React, { useRef } from 'react'

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.Mesh
    niddle: THREE.Mesh
    niddle001: THREE.Mesh
    topring: THREE.Mesh
    topring001: THREE.Mesh
    topring002: THREE.Mesh
    topring003: THREE.Mesh
    topring004: THREE.Mesh
    topring005: THREE.Mesh
    topring006: THREE.Mesh
    topring007: THREE.Mesh
    topring008: THREE.Mesh
    topring009: THREE.Mesh
    topring010: THREE.Mesh
    topring011: THREE.Mesh
    topring012: THREE.Mesh
    topring013: THREE.Mesh
    topring014: THREE.Mesh
    bottomring: THREE.Mesh
    bottomring001: THREE.Mesh
    bottomring002: THREE.Mesh
    bottomring003: THREE.Mesh
    bottomring004: THREE.Mesh
    bottomring005: THREE.Mesh
    bottomring006: THREE.Mesh
    bottomring007: THREE.Mesh
    bottomring008: THREE.Mesh
    bottomring009: THREE.Mesh
    bottomring010: THREE.Mesh
    bottomring011: THREE.Mesh
    bottomring012: THREE.Mesh
    bottomring013: THREE.Mesh
    bottomring014: THREE.Mesh
    bottomring015: THREE.Mesh
    topring015: THREE.Mesh
  }
  materials: {
    blinn2: THREE.MeshStandardMaterial
    niddle1: THREE.MeshStandardMaterial
    knit_fabric: THREE.MeshStandardMaterial
  }
}

export function Purl2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/purl/purl2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-5.36, -1.82, 2.62]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.blinn2}
          scale={0.01}
        />
      </group>
      <mesh
        geometry={nodes.niddle.geometry}
        material={materials.niddle1}
        position={[-2, 0.09, 3.03]}
        rotation={[0.24, -0.13, -2.13]}
        scale={[-0.1, -1.81, -0.1]}
      />
      <mesh
        geometry={nodes.niddle001.geometry}
        material={materials.niddle1}
        position={[-4.41, -0.06, 2.66]}
        rotation={[0.04, -0.19, 2.25]}
        scale={[-0.1, -1.81, -0.1]}
      />
      <mesh
        geometry={nodes.topring.geometry}
        material={materials.knit_fabric}
        position={[4.09, 2.53, -0.21]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring001.geometry}
        material={materials.knit_fabric}
        position={[4, 2.58, -0.21]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring002.geometry}
        material={materials.knit_fabric}
        position={[3.91, 2.63, -0.2]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring003.geometry}
        material={materials.knit_fabric}
        position={[3.83, 2.68, -0.2]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring004.geometry}
        material={materials.knit_fabric}
        position={[3.75, 2.74, -0.19]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring005.geometry}
        material={materials.knit_fabric}
        position={[3.66, 2.79, -0.19]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring006.geometry}
        material={materials.knit_fabric}
        position={[3.57, 2.84, -0.18]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring007.geometry}
        material={materials.knit_fabric}
        position={[3.49, 2.89, -0.18]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring008.geometry}
        material={materials.knit_fabric}
        position={[3.4, 2.95, -0.17]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring009.geometry}
        material={materials.knit_fabric}
        position={[3.32, 3, -0.16]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring010.geometry}
        material={materials.knit_fabric}
        position={[3.23, 3.05, -0.16]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring011.geometry}
        material={materials.knit_fabric}
        position={[3.15, 3.1, -0.15]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring012.geometry}
        material={materials.knit_fabric}
        position={[3.06, 3.15, -0.15]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring013.geometry}
        material={materials.knit_fabric}
        position={[2.98, 3.2, -0.14]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.topring014.geometry}
        material={materials.knit_fabric}
        position={[2.89, 3.26, -0.14]}
        rotation={[0.01, 0.06, -0.55]}
      />
      <mesh
        geometry={nodes.bottomring.geometry}
        material={materials.knit_fabric}
        position={[-4.21, 3.6, 4.24]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring001.geometry}
        material={materials.knit_fabric}
        position={[-4.29, 3.65, 4.24]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring002.geometry}
        material={materials.knit_fabric}
        position={[-4.38, 3.7, 4.25]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring003.geometry}
        material={materials.knit_fabric}
        position={[-4.46, 3.75, 4.25]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring004.geometry}
        material={materials.knit_fabric}
        position={[-4.55, 3.81, 4.26]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring005.geometry}
        material={materials.knit_fabric}
        position={[-4.63, 3.86, 4.26]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring006.geometry}
        material={materials.knit_fabric}
        position={[-4.72, 3.91, 4.27]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring007.geometry}
        material={materials.knit_fabric}
        position={[-4.8, 3.96, 4.27]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring008.geometry}
        material={materials.knit_fabric}
        position={[-4.9, 4.02, 4.28]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring009.geometry}
        material={materials.knit_fabric}
        position={[-4.98, 4.07, 4.29]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring010.geometry}
        material={materials.knit_fabric}
        position={[-5.07, 4.12, 4.29]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring011.geometry}
        material={materials.knit_fabric}
        position={[-5.15, 4.17, 4.3]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring012.geometry}
        material={materials.knit_fabric}
        position={[-5.24, 4.22, 4.3]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring013.geometry}
        material={materials.knit_fabric}
        position={[-5.32, 4.27, 4.31]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring014.geometry}
        material={materials.knit_fabric}
        position={[-5.41, 4.33, 4.31]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring015.geometry}
        material={materials.knit_fabric}
        position={[-5.49, 4.37, 4.31]}
        rotation={[0.01, 0.06, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.topring015.geometry}
        material={materials.knit_fabric}
        position={[2.8, 3.31, -0.13]}
        rotation={[0.01, 0.06, -0.55]}
      />
    </group>
  )
}

useGLTF.preload('/purl_2_complete-transformed.glb')
