/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 knit2.glb -t
*/

import React, { useRef } from 'react'

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.Mesh
    niddle: THREE.Mesh
    niddle001: THREE.Mesh
    topring: THREE.Mesh
    topring001: THREE.Mesh
    topring002: THREE.Mesh
    topring003: THREE.Mesh
    topring004: THREE.Mesh
    topring005: THREE.Mesh
    topring006: THREE.Mesh
    topring007: THREE.Mesh
    topring008: THREE.Mesh
    topring009: THREE.Mesh
    topring010: THREE.Mesh
    topring011: THREE.Mesh
    topring012: THREE.Mesh
    topring013: THREE.Mesh
    topring014: THREE.Mesh
    bottomring: THREE.Mesh
    bottomring001: THREE.Mesh
    bottomring002: THREE.Mesh
    bottomring003: THREE.Mesh
    bottomring004: THREE.Mesh
    bottomring005: THREE.Mesh
    bottomring006: THREE.Mesh
    bottomring007: THREE.Mesh
    bottomring008: THREE.Mesh
    bottomring009: THREE.Mesh
    bottomring010: THREE.Mesh
    bottomring011: THREE.Mesh
    bottomring012: THREE.Mesh
    bottomring013: THREE.Mesh
    bottomring014: THREE.Mesh
    bottomring015: THREE.Mesh
    topring015: THREE.Mesh
    topring016: THREE.Mesh
  }
  materials: {
    blinn2: THREE.MeshStandardMaterial
    niddle1: THREE.MeshStandardMaterial
    knit_fabric: THREE.MeshStandardMaterial
  }
}

export function Knit2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/knit/knit2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-5.36, -1.82, 2.62]} rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.01}>
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.blinn2}
            position={[3.52, 278.27, 125.81]}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.niddle.geometry}
        material={materials.niddle1}
        position={[-2.03, 0.14, 2.96]}
        rotation={[0.24, -0.14, -2.14]}
        scale={[-0.1, -1.81, -0.1]}
      />
      <mesh
        geometry={nodes.niddle001.geometry}
        material={materials.niddle1}
        position={[-3.8, -0.27, 2.31]}
        rotation={[0.23, -0.88, 2.64]}
        scale={[-0.1, -1.81, -0.1]}
      />
      <mesh
        geometry={nodes.topring.geometry}
        material={materials.knit_fabric}
        position={[4.11, 2.5, -0.16]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring001.geometry}
        material={materials.knit_fabric}
        position={[4.02, 2.55, -0.15]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring002.geometry}
        material={materials.knit_fabric}
        position={[3.94, 2.6, -0.15]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring003.geometry}
        material={materials.knit_fabric}
        position={[3.86, 2.65, -0.15]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring004.geometry}
        material={materials.knit_fabric}
        position={[3.77, 2.71, -0.14]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring005.geometry}
        material={materials.knit_fabric}
        position={[3.68, 2.76, -0.14]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring006.geometry}
        material={materials.knit_fabric}
        position={[3.6, 2.81, -0.13]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring007.geometry}
        material={materials.knit_fabric}
        position={[3.52, 2.86, -0.13]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring008.geometry}
        material={materials.knit_fabric}
        position={[3.42, 2.92, -0.12]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring009.geometry}
        material={materials.knit_fabric}
        position={[3.34, 2.97, -0.12]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring010.geometry}
        material={materials.knit_fabric}
        position={[3.25, 3.03, -0.11]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring011.geometry}
        material={materials.knit_fabric}
        position={[3.17, 3.08, -0.11]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring012.geometry}
        material={materials.knit_fabric}
        position={[3.08, 3.13, -0.1]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring013.geometry}
        material={materials.knit_fabric}
        position={[3, 3.18, -0.1]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring014.geometry}
        material={materials.knit_fabric}
        position={[2.91, 3.24, -0.09]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.bottomring.geometry}
        material={materials.knit_fabric}
        position={[-4.23, 3.62, 4.2]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring001.geometry}
        material={materials.knit_fabric}
        position={[-4.32, 3.67, 4.2]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring002.geometry}
        material={materials.knit_fabric}
        position={[-4.4, 3.72, 4.2]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring003.geometry}
        material={materials.knit_fabric}
        position={[-4.48, 3.77, 4.21]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring004.geometry}
        material={materials.knit_fabric}
        position={[-4.57, 3.83, 4.21]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring005.geometry}
        material={materials.knit_fabric}
        position={[-4.65, 3.88, 4.22]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring006.geometry}
        material={materials.knit_fabric}
        position={[-4.74, 3.93, 4.22]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring007.geometry}
        material={materials.knit_fabric}
        position={[-4.82, 3.98, 4.23]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring008.geometry}
        material={materials.knit_fabric}
        position={[-4.92, 4.04, 4.23]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring009.geometry}
        material={materials.knit_fabric}
        position={[-5, 4.09, 4.24]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring010.geometry}
        material={materials.knit_fabric}
        position={[-5.09, 4.15, 4.24]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring011.geometry}
        material={materials.knit_fabric}
        position={[-5.17, 4.2, 4.25]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring012.geometry}
        material={materials.knit_fabric}
        position={[-5.26, 4.25, 4.25]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring013.geometry}
        material={materials.knit_fabric}
        position={[-5.34, 4.3, 4.26]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring014.geometry}
        material={materials.knit_fabric}
        position={[-5.43, 4.36, 4.26]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.bottomring015.geometry}
        material={materials.knit_fabric}
        position={[-5.51, 4.4, 4.25]}
        rotation={[0.02, 0.04, -0.55]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.topring015.geometry}
        material={materials.knit_fabric}
        position={[2.83, 3.29, -0.09]}
        rotation={[0.02, 0.04, -0.55]}
      />
      <mesh
        geometry={nodes.topring016.geometry}
        material={materials.knit_fabric}
        position={[2.89, 3.26, -0.08]}
        rotation={[0.02, 0.04, -0.55]}
      />
    </group>
  )
}

useGLTF.preload('/knit2.glb')
